### ISSUE TITLE
TTN Cli uplink simulate command  fails randomly

### ISSUE THREAD

**Issue by cheribhai** [TheThingsNetwork/lorawan-stack#2210]
#### Summary
The TTN Cli tool gives random failures when using the uplink simulate command. 
There does not seem to be a discernible pattern to it.

#### Steps to Reproduce
Run the TTN Cli uplink command ...
```
ttn-lw-cli simulate uplink \
    --confirmed \
    --dev-addr $DEV_ADDR \
    --f-nwk-s-int-key $NWK_S_KEY \
    --app-s-key $APP_S_KEY \
    --gateway-id $GTW_ID \
    --frm-payload 4869 \
    --lorawan-version $LORAWAN_VERSION \
    --lorawan-phy-version $LORAWAN_PHY_VERSION \
    --log.level debug \
    --band-id $FREQ_PLAN \
    --bandwidth 125000 \
    --frequency 868500000 \
    --spreading-factor 7 \
    --f-cnt $2
```
... a number of times and and some point you will see an error (segmentation fault)

#### What do you see now?
The following output (occurs randomly but frequently)
```
 DEBUG Using access token (valid until 7:00PM) 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x13c7ed5]

goroutine 1 [running]:
go.thethings.network/lorawan-stack/cmd/ttn-lw-cli/commands.(*simulateMetadataParams).setDefaults(0xc00009b6d0, 0xc00009b6d0, 0xc0001cbb00)
	/home/travis/gopath/src/go.thethings.network/lorawan-stack/cmd/ttn-lw-cli/commands/simulate.go:98 +0x2f5
go.thethings.network/lorawan-stack/cmd/ttn-lw-cli/commands.glob..func113(0x26b2220, 0xc0003d0700, 0x0, 0x1b, 0x0, 0x0)
	/home/travis/gopath/src/go.thethings.network/lorawan-stack/cmd/ttn-lw-cli/commands/simulate.go:500 +0x97
github.com/spf13/cobra.(*Command).execute(0x26b2220, 0xc0003d0540, 0x1b, 0x1c, 0x26b2220, 0xc0003d0540)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x26b1a40, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
main.main()
	/home/travis/gopath/src/go.thethings.network/lorawan-stack/cmd/ttn-lw-cli/main.go:27 +0x31
```

#### What do you want to see instead?
The command executing succesfully.

#### Environment
: ttn-lw-cli version
The Things Network Command-line Interface: ttn-lw-cli
Version: 3.6.1
Build date: 2020-03-13T11:26:42Z
Git commit: 8be6823
Go version: go1.13.8
OS/Arch: linux/amd64

**Comment by johanstokking** [comment]
Thanks for reporting. I saw this too when reproducing your issue in #2178.

I fixed this already in https://github.com/TheThingsNetwork/lorawan-stack/pull/2209. It's not released yet; it will be in `v3.7.0-rc2` or `v3.7.0`. Otherwise you can `go get go.thethings.network/lorawan-stack/cmd/ttn-lw-cli` (needs Go, see https://golang.org/dl/).
