### ISSUE TITLE
Flaky AS NATS test

### ISSUE THREAD

**Issue by htdvisser** [TheThingsNetwork/lorawan-stack#2847]
#### Summary

I encountered a flaky test in the AS NATS package.

#### What do you see now?

```
--- FAIL: TestOpenConnection (2.08s)
    doc.go:66: 
        /home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/applicationserver/io/pubsub/provider/nats/provider_test.go:164
        Expected: nil
        Actual:   'context deadline exceeded'
    doc.go:66: 
        /home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/applicationserver/io/pubsub/provider/nats/provider_test.go:165
        Expected '<nil>' to NOT be nil (but it was)!
    --- FAIL: TestOpenConnection/Downstream (2.05s)
        --- FAIL: TestOpenConnection/Downstream/ValidPush (2.05s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x136fc6d]
goroutine 40 [running]:
testing.tRunner.func1.1(0x14882e0, 0x25672b0)
	/home/travis/.gimme/versions/go1.14.4.linux.amd64/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc000558360)
	/home/travis/.gimme/versions/go1.14.4.linux.amd64/src/testing/testing.go:943 +0x3f9
panic(0x14882e0, 0x25672b0)
	/home/travis/.gimme/versions/go1.14.4.linux.amd64/src/runtime/panic.go:969 +0x166
go.thethings.network/lorawan-stack/v3/pkg/applicationserver/io/pubsub/provider/nats_test.TestOpenConnection.func1.1(0xc000558360)
	/home/travis/gopath/src/go.thethings.network/lorawan-stack/pkg/applicationserver/io/pubsub/provider/nats/provider_test.go:167 +0x2ed
testing.tRunner(0xc000558360, 0xc00053e330)
	/home/travis/.gimme/versions/go1.14.4.linux.amd64/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.14.4.linux.amd64/src/testing/testing.go:1042 +0x357
FAIL	go.thethings.network/lorawan-stack/v3/pkg/applicationserver/io/pubsub/provider/nats	2.108s
```

**Comment by htdvisser** [comment]
+1 in https://github.com/TheThingsNetwork/lorawan-stack/runs/945383962
